# values.yaml

namespace: student-app
frontend:
  enabled: true
  image:
    repository: duong3010/fe-image
    tag: "v2.9"
  replicaCount: 1
  containerPort: 80
  service:
    type: NodePort
    port: 80
    nodePort: 8010
backend:
  enabled: true
  image:
    repository: duong3010/be-image
    tag: "v2.9"
  replicaCount: 1
  containerPort: 3000
  service:
    type: NodePort
    port: 3000
    nodePort: 8011
  env:
    DB_HOST: "192.168.56.112"
    DB_PORT: "8006"
    DB_USER: "duongnv"
    DB_PASSWORD: "duongnv"
    DB_NAME: "db"
    JWT_SECRET: "secretkey"
